# Generated by Django 6.0.2 on 2026-03-06 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
        ('quality_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditanswer',
            name='linked_capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='capa.caparecord'),
        ),
    ]
