# Generated by Django 6.0.2 on 2026-02-26 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('position_title', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], max_length=20)),
                ('reason', models.CharField(choices=[('NEW', 'New Position'), ('REPLACEMENT', 'Replacement')], max_length=20)),
                ('replacement_for', models.CharField(blank=True, help_text='If replacement, who are they replacing?', max_length=200, null=True)),
                ('proposed_start_date', models.DateField()),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_description', models.TextField()),
                ('qualifications', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Position Filled')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from HR/Management')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
