# Generated by Django 6.0.2 on 2026-02-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_hiringrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='justification',
            field=models.TextField(default='Provided justification for initial request.', help_text='Detailed justification for this hire'),
            preserve_default=False,
        ),
    ]
