# Generated by Django 6.0.2 on 2026-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZiG', 'ZiG')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='medical_aid/%Y/%m/'),
        ),
    ]
