# Generated by Django 6.0.2 on 2026-02-13 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_aid', '0002_preauthorizationrequest_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preauthorizationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Preauthorization Request', 'verbose_name_plural': 'Preauthorization Requests'},
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='attending_doctor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Attending / Treating Doctor'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='auth_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Auth Number (from Scheme)'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='clinical_notes',
            field=models.TextField(blank=True, verbose_name='Clinical Notes / Justification'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='diagnosis',
            field=models.TextField(default='', verbose_name='Diagnosis / Clinical Indication'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='facility_name',
            field=models.CharField(default='Mater Dei Hospital', max_length=120, verbose_name='Facility Name'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='icd_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ICD-11 Code'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Emergency Request'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='member_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Member Number'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='patient_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='patient_name',
            field=models.CharField(default='', max_length=120, verbose_name='Patient Full Name'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='principal_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Principal Member Name'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='procedure_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Procedure Code (CPT)'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='referring_doctor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Referring Doctor'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Dependant', 'Dependant')], max_length=20, verbose_name='Relationship to Principal'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='scheme_plan',
            field=models.CharField(blank=True, max_length=60, verbose_name='Plan / Tier'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_aid_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Cost'),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='patient_id',
            field=models.CharField(max_length=20, verbose_name='Patient/Member ID'),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='procedure',
            field=models.CharField(max_length=200, verbose_name='Procedure / Treatment Requested'),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='scheme',
            field=models.CharField(choices=[('PSMAS', 'PSMAS'), ('CIMAS', 'CIMAS'), ('FIRST_MUTUAL', 'First Mutual'), ('CELLMED', 'Cellmed'), ('FIDELITY', 'Fidelity Life'), ('MASCA', 'MASCA'), ('OTHER', 'Other')], max_length=50, verbose_name='Medical Aid Scheme'),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='medical_aid/%Y/%m/', verbose_name='Supporting Document'),
        ),
    ]
