# Generated by Django 6.0.2 on 2026-02-13 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_aid', '0003_alter_preauthorizationrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At'),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='email_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_aid_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='sent_to_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sent To Email'),
        ),
    ]
