# Generated by Django 6.0.1 on 2026-04-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_aid', '0004_preauthorizationrequest_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='facility_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Facility Name'),
        ),
    ]
