# Generated by Django 6.0.2 on 2026-05-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_shifthandover_assessment_shifthandover_background_and_more'),
        ('medical_aid', '0005_alter_preauthorizationrequest_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorizationrequest',
            name='patient_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preauth_requests', to='clinical.patient'),
        ),
    ]
