# Generated by Django 6.0.1 on 2026-02-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('sop_manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='linked_document',
            field=models.ForeignKey(blank=True, help_text='Link to an existing document from the Documents section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sops', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='sop',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='Direct upload (Legacy)', null=True, upload_to='sops/'),
        ),
    ]
