# Generated by Django 6.0.2 on 2026-02-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sop_manual', '0002_sop_linked_document_alter_sop_file_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SOPAcknowledgment',
        ),
    ]
