# Generated by Django 6.0.2 on 2026-03-06 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('medical_aid_name', models.CharField(blank=True, max_length=100)),
                ('medical_aid_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subjective', models.TextField(verbose_name="Subjective (Patient's complaints)")),
                ('objective', models.TextField(verbose_name='Objective (Physical findings)')),
                ('assessment', models.TextField(verbose_name='Assessment (Diagnosis/ICD-11)')),
                ('plan', models.TextField(verbose_name='Plan (Treatments/Referrals)')),
                ('icd11_diagnosis', models.CharField(blank=True, help_text='Primary ICD-11 code', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_history', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('collecting', 'Sample Collecting'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('results_ready', models.BooleanField(default=False)),
                ('results_url', models.URLField(blank=True, help_text='Link to result document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='clinical.consultation')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_lab_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('specimen_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='clinical.labrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Dispensing'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.consultation')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_by', to=settings.AUTH_USER_MODEL)),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('total_quantity', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.prescription')),
            ],
        ),
    ]
