# Generated by Django 6.0.2 on 2026-03-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('capturing', 'Ongoing Capture'), ('interpreting', 'Interpretation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('report_ready', models.BooleanField(default=False)),
                ('results_url', models.URLField(blank=True, help_text='Link to DICOM/PACS viewer or report PDF')),
                ('imaging_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_requests', to='clinical.consultation')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_imaging_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('other', 'Other')], max_length=100)),
                ('view_area', models.CharField(help_text='e.g. Chest AP/Lateral, Right Knee', max_length=200)),
                ('clinical_question', models.TextField(blank=True)),
                ('imaging_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.imagingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('elective', 'Elective'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='elective', max_length=20)),
                ('proposed_date', models.DateTimeField()),
                ('estimated_duration', models.IntegerField(default=60, help_text='Estimated minutes')),
                ('assistant_surgeon', models.CharField(blank=True, max_length=255)),
                ('anaesthetist', models.CharField(blank=True, max_length=255)),
                ('theatre_number', models.CharField(blank=True, max_length=50)),
                ('theatre_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pre-op', 'Pre-Op Preparation'), ('in-theatre', 'In Theatre'), ('post-op', 'Post-Op / Recovery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_bookings', to='clinical.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patient')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_theatre_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
