# Generated by Django 6.0.2 on 2026-03-06 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_chroniccondition_patientallergy_patientvitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('drug_class', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medication_name',
            field=models.CharField(help_text='Used if Medication model is not selected', max_length=200),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.medication'),
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major / Contraindicated')], max_length=20)),
                ('warning_message', models.TextField()),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_a', to='clinical.medication')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_b', to='clinical.medication')),
            ],
            options={
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
    ]
