# Generated by Django 6.0.2 on 2026-03-06 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_medication_alter_prescriptionitem_medication_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitals',
            name='is_trauma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='level_of_consciousness',
            field=models.CharField(choices=[('A', 'Alert'), ('V', 'Voice'), ('P', 'Pain'), ('U', 'Unresponsive')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='mobility',
            field=models.CharField(choices=[('walking', 'Walking'), ('with_help', 'With Help'), ('stretcher', 'Stretcher/Immobile')], default='walking', max_length=20),
        ),
        migrations.CreateModel(
            name='FluidBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('oral_intake', models.IntegerField(default=0, help_text='ml')),
                ('iv_intake', models.IntegerField(default=0, help_text='ml')),
                ('urine_output', models.IntegerField(default=0, help_text='ml')),
                ('drain_output', models.IntegerField(default=0, help_text='ml')),
                ('emesis', models.IntegerField(default=0, help_text='ml')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_balances', to='clinical.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('situation', models.TextField()),
                ('background', models.TextField(blank=True)),
                ('assessment', models.TextField()),
                ('recommendation', models.TextField()),
                ('dressing_done', models.BooleanField(default=False)),
                ('wound_care_notes', models.TextField(blank=True)),
                ('pain_score', models.IntegerField(blank=True, help_text='0-10 Scale', null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(default=django.utils.timezone.now)),
                ('shift_type', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], max_length=10)),
                ('general_ward_notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('outgoing_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ManyToManyField(related_name='handovers', to='clinical.patient')),
            ],
        ),
    ]
