# Generated by Django 6.0.2 on 2026-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_patientvitals_is_trauma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingrequest',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='clinical/imaging_reports/'),
        ),
        migrations.AlterField(
            model_name='imagingrequest',
            name='results_url',
            field=models.URLField(blank=True, help_text='Link to DICOM/PACS viewer'),
        ),
    ]
