# Generated by Django 6.0.2 on 2026-04-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_imagingrequest_report_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifthandover',
            name='assessment',
            field=models.TextField(blank=True, help_text='Clinical overview of critical patients or concerns'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='background',
            field=models.TextField(blank=True, help_text='Relevant history since last shift (e.g. admissions, discharges)'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Action plan for the incoming shift'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='situation',
            field=models.TextField(blank=True, help_text='Current ward status, staffing, or major events'),
        ),
    ]
