# Generated by Django 6.0.2 on 2026-02-23 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident_log', '0003_incident_attachment'),
        ('sop_manual', '0002_sop_linked_document_alter_sop_file_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('capa_type', models.CharField(choices=[('corrective', 'Corrective Action'), ('preventive', 'Preventive Action'), ('both', 'Corrective & Preventive')], default='corrective', max_length=20)),
                ('source', models.CharField(choices=[('incident', 'Incident Report'), ('audit', 'Internal Audit'), ('complaint', 'Patient Complaint'), ('inspection', 'External Inspection'), ('observation', 'Staff Observation'), ('trend', 'Data Trend Analysis'), ('regulatory', 'Regulatory Requirement'), ('other', 'Other')], default='incident', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('investigation', 'Under Investigation'), ('action_planning', 'Action Planning'), ('implementation', 'Implementation'), ('verification', 'Effectiveness Verification'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the non-conformance or issue')),
                ('impact_assessment', models.TextField(blank=True, help_text='What is the impact on patients, staff, operations?')),
                ('root_cause_method', models.CharField(blank=True, choices=[('5_whys', '5 Whys'), ('fishbone', 'Fishbone / Ishikawa'), ('fmea', 'FMEA'), ('pareto', 'Pareto Analysis'), ('fault_tree', 'Fault Tree Analysis'), ('other', 'Other')], help_text='Root cause analysis methodology used', max_length=50)),
                ('root_cause_analysis', models.TextField(blank=True, help_text='Detailed root cause analysis findings')),
                ('root_cause_summary', models.CharField(blank=True, help_text='One-line summary of the root cause', max_length=500)),
                ('contributing_factors', models.TextField(blank=True, help_text='Additional contributing factors')),
                ('immediate_containment', models.TextField(blank=True, help_text='Immediate actions taken to contain the issue')),
                ('corrective_action_plan', models.TextField(blank=True, help_text='Detailed plan for corrective actions')),
                ('preventive_action_plan', models.TextField(blank=True, help_text='Actions to prevent recurrence')),
                ('verification_criteria', models.TextField(blank=True, help_text='How will we verify the actions were effective?')),
                ('verification_results', models.TextField(blank=True, help_text='Results of effectiveness verification')),
                ('is_effective', models.BooleanField(blank=True, help_text='Were the actions effective in resolving the issue?', null=True)),
                ('target_completion_date', models.DateField(blank=True, help_text='Target date to complete all actions', null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, help_text='Supporting evidence or documentation', null=True, upload_to='capa/%Y/%m/')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person responsible for this CAPA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_capas', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_capas', to=settings.AUTH_USER_MODEL)),
                ('linked_incident', models.ForeignKey(blank=True, help_text='Originating incident (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_records', to='incident_log.incident')),
                ('related_sops', models.ManyToManyField(blank=True, help_text='SOPs that need to be updated as a result', related_name='related_capas', to='sop_manual.sop')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Person who verified effectiveness', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_capas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPA Record',
                'verbose_name_plural': 'CAPA Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPAComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='capa.caparecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['status', '-created_at'], name='capa_capare_status_dcb8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['priority', '-created_at'], name='capa_capare_priorit_648ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='caparecord',
            index=models.Index(fields=['assigned_to', 'status'], name='capa_capare_assigne_05475d_idx'),
        ),
    ]
