# Generated by Django 6.0.2 on 2026-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='target_app',
            field=models.CharField(choices=[('all', 'General / All Modules'), ('clinical', 'Clinical (Patients/Consultations)'), ('icd11', 'ICD-11 Coding Tools'), ('medical_aid', 'Medical Aid / Billing'), ('hr', 'Human Resources'), ('finance', 'Finance & Accounting'), ('fleet', 'Fleet Management'), ('maintenance', 'Maintenance'), ('quality', 'Quality & Compliance'), ('sops', 'Standard Operating Procedures')], default='all', help_text='Module where documents in this category will be automatically mapped', max_length=50),
        ),
    ]
