# Generated by Django 6.0.2 on 2026-02-23 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sop_manual', '0002_sop_linked_document_alter_sop_file_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Describe when this template should be used')),
                ('category', models.CharField(choices=[('clinical', 'Clinical Procedure'), ('nursing', 'Nursing Protocol'), ('laboratory', 'Laboratory Procedure'), ('pharmacy', 'Pharmacy Protocol'), ('admin', 'Administrative Procedure'), ('infection_control', 'Infection Control'), ('emergency', 'Emergency Response'), ('radiology', 'Radiology Procedure'), ('surgical', 'Surgical Procedure'), ('general', 'General Operations')], default='general', max_length=30)),
                ('icon', models.CharField(default='fas fa-file-alt', help_text='FontAwesome icon class', max_length=60)),
                ('is_clinical', models.BooleanField(default=False, help_text='If True, ICD-11 code fields are shown')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('sections_json', models.TextField(default='[]', help_text='JSON array defining the template sections')),
                ('formatting_rules_json', models.TextField(default='{}', help_text='JSON object defining MDH formatting requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SOPDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('template_selected', 'Template Selected'), ('drafting', 'Drafting in Progress'), ('icd_review', 'ICD-11 Review'), ('validating', 'Validation in Progress'), ('validated', 'Validated'), ('needs_revision', 'Needs Revision'), ('ready', 'Ready for Publication'), ('published', 'Published to SOP Manual'), ('discarded', 'Discarded')], default='template_selected', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('icd_codes_json', models.TextField(default='[]', help_text='JSON array of ICD-11 code objects [{code, description}]')),
                ('validation_score', models.IntegerField(default=0, help_text='0-100 validation score')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('compiled_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_drafts', to=settings.AUTH_USER_MODEL)),
                ('published_sop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='sop_manual.sop')),
                ('target_category', models.ForeignKey(blank=True, help_text='Target SOP Manual category for publication', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sop_manual.sopcategory')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='sop_assistant.soptemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(help_text='e.g. MDH-FMT-001, ICD-REQ-001', max_length=50)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Pass')], max_length=10)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='sop_assistant.sopdraft')),
            ],
            options={
                'ordering': ['severity', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='SOPDraftSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=50)),
                ('section_label', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sop_assistant.sopdraft')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('draft', 'section_key')},
            },
        ),
    ]
