# Generated by Django 6.0.2 on 2026-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
        ('incident_log', '0003_incident_attachment'),
        ('sop_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sopdraft',
            name='referenced_capas',
            field=models.ManyToManyField(blank=True, related_name='sop_drafts', to='capa.caparecord'),
        ),
        migrations.AddField(
            model_name='sopdraft',
            name='referenced_incidents',
            field=models.ManyToManyField(blank=True, related_name='sop_drafts', to='incident_log.incident'),
        ),
    ]
