# Generated by Django 6.0.1 on 2026-04-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_assistant', '0002_sopdraft_referenced_capas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soptemplate',
            name='formatting_rules_json',
            field=models.TextField(default='{}', help_text='JSON object defining OpsHub formatting requirements'),
        ),
        migrations.AlterField(
            model_name='validationresult',
            name='rule_code',
            field=models.CharField(help_text='e.g. FMT-001, ICD-REQ-001', max_length=50),
        ),
    ]
