# Generated by Django 6.0.2 on 2026-02-26 21:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('AMBULANCE', 'Ambulance'), ('PATIENT_TRANSPORT', 'Patient Transport'), ('UTILITY', 'Utility / Delivery'), ('EXECUTIVE', 'Executive Staff')], default='AMBULANCE', max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_TRANSIT', 'In Transit'), ('MAINTENANCE', 'In Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('current_mileage', models.IntegerField(default=0, help_text='Current odometer reading in km')),
                ('registration_expiry', models.DateField()),
                ('insurance_expiry', models.DateField()),
                ('next_service_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-status', 'vehicle_type'],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_mileage', models.IntegerField()),
                ('end_mileage', models.IntegerField(blank=True, null=True)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('purpose', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet_management.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total cost in local currency', max_digits=10)),
                ('odometer', models.IntegerField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='fuel_receipts/')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet_management.vehicle')),
            ],
        ),
    ]
