# Generated by Django 6.0.1 on 2026-02-13 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date_reported'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member investigating this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('patient_fall', 'Patient Fall'), ('medication_error', 'Medication Error'), ('equipment_failure', 'Equipment Failure'), ('staff_injury', 'Staff Injury'), ('infection_control', 'Infection Control'), ('security_breach', 'Security Breach'), ('near_miss', 'Near Miss'), ('it_issue', 'IT / System Issue'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='corrective_actions',
            field=models.TextField(blank=True, help_text='Steps taken to prevent recurrence'),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_occurred',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the incident occurred'),
        ),
        migrations.AddField(
            model_name='incident',
            name='immediate_action',
            field=models.TextField(blank=True, help_text='Immediate action taken at the time'),
        ),
        migrations.AddField(
            model_name='incident',
            name='persons_involved',
            field=models.TextField(blank=True, help_text='Names/IDs of people involved in the incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='witnesses',
            field=models.TextField(blank=True, help_text='Names of witnesses'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolution_notes',
            field=models.TextField(blank=True, default=django.utils.timezone.now, help_text='How the incident was resolved'),
            preserve_default=False,
        ),
    ]
