# Generated by Django 6.0.2 on 2026-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_log', '0002_alter_incident_options_incident_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload evidence or photos', null=True, upload_to='incidents/%Y/%m/'),
        ),
    ]
