# Generated by Django 6.0.2 on 2026-05-11 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_log', '0004_incident_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='involved_contractor',
            field=models.CharField(blank=True, help_text='Name of contractor or company involved', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='involved_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='involved_type',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('EMPLOYEE', 'Employee / Staff'), ('CONTRACTOR', 'Contractor'), ('VISITOR', 'Visitor'), ('OTHER', 'Other / Property')], default='OTHER', max_length=20),
        ),
    ]
