# Generated by Django 6.0.2 on 2026-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/'),
        ),
    ]
