# Generated by Django 6.0.2 on 2026-02-26 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='Serial Number/Tag')),
                ('category', models.CharField(help_text='e.g. HVAC, Lab Equip, Electrical', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DOWN', 'Out of Service'), ('MAINTENANCE', 'In Maintenance'), ('RETIRED', 'Retired')], default='OPERATIONAL', max_length=20)),
                ('criticality', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_ppm_date', models.DateField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True)),
                ('manual_url', models.URLField(blank=True, verbose_name='Link to Manual')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('frequency_days', models.IntegerField(help_text='Days between service (e.g. 30 for monthly)')),
                ('estimated_duration_mins', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='AssetReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(help_text='e.g. Temperature, Runtime, Pressure', max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='maintenance.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order_type', models.CharField(choices=[('PPM', 'Planned Preventive'), ('REACTIVE', 'Corrective/Repair'), ('PREDICTIVE', 'Predictive Alert'), ('UPGRADE', 'Upgrade/Install')], default='REACTIVE', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open/New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold/Waiting Parts'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='maintenance.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance_attachments/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.workorder')),
            ],
        ),
    ]
